### ISSUE TITLE
create public docker image on dockerhub

### ISSUE THREAD

**Issue by kktam** [oracle/oci-designer-toolkit#498] opened 2021-11-21 04:42 UTC
Can the Oracle OCI team create a public and regularly maintained  docker image of this project (OKIT) on dockerhub, as well as in the OCI Container Registry (OCIR).

**Comment by toxophilist** [comment] 2022-04-26 09:28
Duplicate of #195

**Comment by toxophilist** [comment] 2024-06-13 14:37
No resources to do this

**Closed by toxophilist** 2024-06-13 14:37 UTC
Labels: duplicate, enhancement, wontfix
