### ISSUE TITLE
unable to create docker image

### ISSUE THREAD

**Issue by xperiazn** [oracle/oci-designer-toolkit#38] opened 2020-07-02 09:07 UTC
when i run this command: docker build --tag okit --file ./containers/docker/Dockerfile --force-rm .
I got following error.

Updated:
  ca-certificates.noarch 0:2020.2.41-70.0.el7_8
  oraclelinux-release-el7.x86_64 0:1.0-12.el7

Complete!
Loaded plugins: ovl
https://yum.oracle.com/repo/OracleLinux/OL7/oci/included/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

 One of the configured repositories failed (OCI specific release packages Oracle Linux 7Server (x86_64)),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=ol7_ociyum_config ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable ol7_ociyum_config
        or
            subscription-manager repos --disable=ol7_ociyum_config

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=ol7_ociyum_config.skip_if_unavailable=true

failure: repodata/repomd.xml from ol7_ociyum_config: [Errno 256] No more mirrors to try.
https://yum.oracle.com/repo/OracleLinux/OL7/oci/included/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Removing intermediate container deebc45b3369
The command '/bin/bash -c yum install -y     oracle-softwarecollection-release-el7  && yum update -y  && yum install -y         python36         python3-pip  && rm -rf /var/cache/yum  && python3 -m pip install --upgrade pip==20.0.2  && pip3 install --no-cache-dir         click==7.0         flask==1.1.1         gunicorn==20.0.4         itsdangerous==1.1.0         jinja2==2.10.3         markupsafe==1.1.1         oci==2.6.0         pyyaml==5.2         werkzeug==0.16.0         cryptography==2.8  && mkdir -p /okit/{config,log,visualiser,okitweb,workspace}' returned a non-zero code: 1

**Comment by toxophilist** [comment] 2020-07-06 14:00
@xperiazn this looks like you can't access the yum repo and I suspect it's due to proxy / routing issues in your environment.

**Comment by xperiazn** [comment] 2020-07-06 14:08
This link is working for you?
https://yum.oracle.com/repo/OracleLinux/OL7/oci/included/x86_64/repodata/repomd.xml

**Comment by toxophilist** [comment] 2020-07-06 15:57
@xperiazn no I can't access that url but I can build the docker container. I suspect you are not able to access the OL Yum repos or it would not be trying alternative mirrors. Hence the comment about routing / proxy.

**Comment by jsalaman** [comment] 2020-07-08 02:34
Check your local yum configuration. Most likely your yum repos are out of date.
Note that the error yuu get is a 404 (not found) and not a timeout (like if where a proxy thing).

**Comment by sskarthikn83** [comment] 2020-07-08 12:26
I have same issue right now and not moving further. I tried to install OCI OKIT Oracle Linux7, Autonomous Linux and CentOS, all reported the same error issue with the repository ol7_ociyum_config. I disabled the repository and even I commented in the oracle-linux-ol7.repo but no luck still.

**Comment by pbattagl** [comment] 2020-07-09 14:32
On OCI cumpute instance, I suspect the issue is related to missing region appended to yum repository file 
ie:
 https://yum$ociregion.oracle.com/repo/OracleLinux/OL7/oci/included/x86_64/ 

ociregion variable is extracted by yum from file /etc/yum/vars/ociregion at run time.
NB: linux kernel used to build image is the one installed by default with docker which you can find below
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
**oraclelinux**         7-slim              7442ca158991        4 weeks ago         120MB

To workaround the issue, I updated dockerfile from oci-designer-toolkit/containers/docker with below entry
# from:
RUN yum install -y \
...
# to:
RUN **echo "-$(curl -sfm 3 http://169.254.169.254/opc/v1/instance/ | grep \"region\"| cut -d '-' -f 2)" > /etc/yum/vars/ociregion \
 &&** yum install -y \
...

image build was successful afterwards.

**Comment by xperiazn** [comment] 2020-07-09 17:24
Thank you @pbattagl,

That definitely solved problem for me.

Maybe there is a problem with images from my (Frankfurt region).
Kind regards

**Comment by padraicr** [comment] 2020-07-14 14:43
This issue is a problem with the underlying OS yum repo configuration, closing the issue.

**Closed by padraicr** 2020-07-14 14:43 UTC
