### ISSUE TITLE
Error with absolute paths in oci config

### ISSUE THREAD

**Issue by fbreckle** [oracle/oci-designer-toolkit#11] opened 2020-05-15 10:06 UTC
When using a full path in the `.oci/config` file, e.g. `key_file=/home/user/.oci/private.pem`, the container throws a `FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.oci/private.pem'`.

This happens because the OCI_CONFIG_DIR is mounted to `/root/.oci` and the full path no longer works in that context, whereas `~/.oci/private.pem` would still work. 

Using a full path works fine with the `oci` cli and the terraform provider. The [cli configuration setup page](https://docs.cloud.oracle.com/en-us/iaas/Content/Functions/Tasks/functionsconfigureocicli.htm) even says `key_file=<full-path-to-private-key-pem-file>` where `<full-path-to-private-key-pem-file> is the full path to the private key file that you created`.
Granted, the example on that page also uses `~/.oci/...` notation, conflicting with the text.

edit: I guess the problem is, whether full path means absolute path or just not-relative path.

**Comment by fbreckle** [comment] 2020-05-15 10:58
I see that is is somehwat a duplicate of #5 
A very simple solution would be to just throw a warning if there is no `~` in the `key_file` value.

**Comment by toxophilist** [comment] 2020-05-15 14:26
Duplicate of Issue #5 documentation updated to add more specific information that the key_file entry must not be an absolute path on the host machine.

**Closed by toxophilist** 2020-05-15 14:26 UTC
